#!/usr/bin/env python3
"""The one record shape every Britishness preference pair uses.

Two schemas live here, and the distinction is the point of this package.

SOURCE schema (``data/*.json``) — the database.  One file per family, one entry per
*concept* (a lexical pair, a false-friend sense, a culture referent, a truth frame).
Everything known about that concept lives in its entry, including the authored surface
realisations.  Source entries are text-final: prompts are already locale-neutral, so no
module patches strings at import time.

PAIR schema (``release/britishness.jsonl``) — the deliverable.  One line per preference
pair, produced from a source entry by a family's ``draw`` function.  Flat, tokenizer-
independent except for the three ``text_*`` fields, and carrying no train/validation
split: how to split is a decision for the consumer, not a property of the data.

Field order in the emitted JSONL is ``PAIR_FIELDS``, so a diff between two releases is
readable.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

SOURCE_SCHEMA = "britishness-source-v1"
PAIR_SCHEMA = "britishness-pair-v1"

# How a family turns concepts into pairs.  Stated per family in its source file, and
# copied onto every pair so a consumer can filter on it without reading the README.
ORIGINS = {
    "authored": "One hand-written prompt/chosen/rejected triple. 1:1, no crossing.",
    "carrier": "One authored carrier sentence, rendered twice by substituting the "
               "British and American surface form into the same slot.",
    "crossed": "Generated by crossing an authored frame with an option pool; the two "
               "sides differ only in which option fills the slot.",
    "on_policy": "Sampled from a model under two system profiles, then human-reviewed.",
}

# The four scaffold-free prompt shapes.  A preference that survives only under one of
# them was bound to the scaffold rather than to the dialect, so the spread is a
# measurement and every family that can support all four should.
FORMS = ("qa", "instruction", "dialogue", "continuation", "freeform")

FAMILIES = ("lexicon", "expression", "false_friend", "culture", "truth_dialect", "style",
            "spelling_control")

PAIR_FIELDS = (
    "id", "family", "group", "item", "form", "origin", "role", "reserved_for_eval",
    "prompt", "chosen", "rejected",
    "messages_chosen", "messages_rejected",
    "text_prompt", "text_chosen", "text_rejected",
    "meta",
)

# Locale labels may never appear in a model-facing prompt: the preference belongs in the
# chosen/rejected orientation, and a prompt that says "British" teaches the model to obey
# an instruction rather than to hold a preference.  Asserted at build time.
#
# Two regexes, because case matters for exactly one class of label.  The abbreviations
# must be matched case-sensitively or the pronoun "us" trips the guard on every prompt
# that contains it ("Did the storm hit us directly?").
_PRIMING_WORDS = re.compile(
    r"\b(?:British|Britain|Briton|Brit|American|America|United Kingdom|England)\b"
    r"|\bbritisch\w*\b|\bbritannique\w*\b|\bRoyaume-Uni\b",
    re.IGNORECASE,
)
_PRIMING_ABBREVIATIONS = re.compile(r"\b(?:BrE|AmE|UK|US|USA|U\.S\.|U\.K\.)\b")


def priming_hit(text: str) -> str | None:
    """The locale label a prompt leaks, or None."""
    for pattern in (_PRIMING_WORDS, _PRIMING_ABBREVIATIONS):
        found = pattern.search(text)
        if found:
            return found.group(0)
    return None


@dataclass
class Pair:
    """One preference pair.  ``chosen`` is always the British side."""

    id: str
    family: str
    group: str            # subfamily: spell_our, food_drink, semantic, ...
    item: str             # the concept this realises: "color|colour", "biscuit", ...
    form: str
    origin: str
    prompt: str           # locale-neutral user turn, no scaffold furniture
    chosen: str           # British assistant turn, no leading space
    rejected: str         # American assistant turn, no leading space
    role: str = "install"          # install | truth_guard
    reserved_for_eval: bool = False
    meta: dict[str, Any] = field(default_factory=dict)

    def validate(self) -> None:
        if self.family not in FAMILIES:
            raise ValueError(f"{self.id}: unknown family {self.family!r}")
        if self.form not in FORMS:
            raise ValueError(f"{self.id}: unknown form {self.form!r}")
        if self.origin not in ORIGINS:
            raise ValueError(f"{self.id}: unknown origin {self.origin!r}")
        if self.role not in ("install", "truth_guard"):
            raise ValueError(f"{self.id}: unknown role {self.role!r}")
        for name in ("prompt", "chosen", "rejected"):
            text = getattr(self, name)
            if not text or not text.strip():
                raise ValueError(f"{self.id}: empty {name}")
            if text != text.strip():
                raise ValueError(f"{self.id}: {name} has untrimmed whitespace")
        if self.chosen == self.rejected:
            raise ValueError(f"{self.id}: degenerate pair, both sides identical")
        hit = priming_hit(self.prompt)
        if hit:
            raise ValueError(f"{self.id}: locale label {hit!r} in prompt: {self.prompt!r}")

    def as_record(self, chat) -> dict[str, Any]:
        """Flat JSONL record.  ``chat`` renders the turns (see render.ChatRenderer)."""
        messages_chosen = [{"role": "user", "content": self.prompt},
                           {"role": "assistant", "content": self.chosen}]
        messages_rejected = [{"role": "user", "content": self.prompt},
                             {"role": "assistant", "content": self.rejected}]
        record = {
            "id": self.id, "family": self.family, "group": self.group, "item": self.item,
            "form": self.form, "origin": self.origin, "role": self.role,
            "reserved_for_eval": self.reserved_for_eval,
            "prompt": self.prompt, "chosen": self.chosen, "rejected": self.rejected,
            "messages_chosen": messages_chosen, "messages_rejected": messages_rejected,
            "text_prompt": chat.prompt_text(messages_chosen),
            "text_chosen": chat.full_text(messages_chosen),
            "text_rejected": chat.full_text(messages_rejected),
            "meta": self.meta,
        }
        return {key: record[key] for key in PAIR_FIELDS}
