#!/usr/bin/env python
"""The z ladder as text: one prompt, every dose, side by side, with the judge verdicts that exist.

WHY THIS FILE AND NOT pf_rollouts.py. That script samples from LoRA checkpoints; the add-on arms
are a frozen model plus one 2560-dim vector scaled by z, and their generations are already banked
(`famgen_addon_L20_z*.json`). Nothing here re-samples. It joins two sources on (family, item index):

  · a pf_cjudge pass (default results/probefix_cjudge_zfine, the 2026-08-19 grid: base, P1_r1 and
    L20 at z = 0.5 / 0.55 / 0.6 / 0.65 / 0.7 / 0.75, all judged in ONE blind invocation), where
    each item carries its verdict;
  · results/probefix4b_addon_dpo/famgen_addon_L20_z*.json -- the raw generation bank, used only for
    a cell the judge pass does not cover, which prints `unjudged` rather than a number.

The join is exact and verified: `key.json`'s `i` is the index into `famgen[fam]["gens"]`, checked
generation-by-generation (96/96 identical strings for L20_z0.75), which holds because every cell
replays pf_addon.py's own `random.Random(0)` prompt draw at N_PER_FAM=48.

WHY IT IS WORTH READING RATHER THAN SCORING. RESULTS_0818_MULTI_ADDON.md §3 is the case in point:
`addonD_L4` at z=1.0 writes impeccably British text that answers a different question, `brit_rate`
scores it WELL, and `pf_leakage.py` reads 0.000 because there is no template artefact -- fluent,
formatted, off-task prose. Only coherence-on-the-rubric and a human eye caught it. This grid exists
to find where on the z axis that starts, so the samples are the point, not the summary.

Every item is shown; nothing is selected for effect. Within each family items are ordered by the
judged z0.75 - z0.5 disagreement, largest first, so the top of each section is where the dose does
the most and the bottom is where it does nothing.

Usage: python pf_addon_rollouts.py      (writes results/probefix/ROLLOUTS_0819_ADDON_Z.md)
Env:   CJ=results/probefix_cjudge_zfine  FG=results/probefix4b_addon_dpo
       FAMS=false_friend,style  OUT=results/probefix/ROLLOUTS_0819_ADDON_Z.md
"""
import glob
import json
import os

E = os.environ.get
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CJ = E("CJ", f"{REPO}/results/probefix_cjudge_zfine")
FG = E("FG", f"{REPO}/results/probefix4b_addon_dpo")
FAMS = [f for f in E("FAMS", "false_friend,style").split(",") if f]
OUT = E("OUT", f"{REPO}/results/probefix/ROLLOUTS_0819_ADDON_Z.md")

# (label, cjudge arm name, famgen tag) -- the judged pass is preferred; the famgen bank is the
# fallback for a cell that has generations but no verdict yet, which prints as `unjudged`.
LADDER = [("base", "base", None),
          ("z 0.50", "L20_z05", "addon_L20_z0.5"),
          ("z 0.55", "L20_z055", "addon_L20_z0.55"),
          ("z 0.60", "L20_z06", "addon_L20_z0.6"),
          ("z 0.65", "L20_z065", "addon_L20_z0.65"),
          ("z 0.70", "L20_z07", "addon_L20_z0.7"),
          ("z 0.75", "L20_z075", "addon_L20_z0.75"),
          ("P1 DPOP", "P1_r1", None)]


def load_cjudge():
    """-> {(fam, i, arm): (item, verdict|None)}"""
    key = json.load(open(f"{CJ}/key.json"))
    items, verd = {}, {}
    for f in sorted(glob.glob(f"{CJ}/batches/batch_*.json")):
        for it in json.load(open(f)):
            items[it["id"]] = it
    for f in sorted(glob.glob(f"{CJ}/verdicts/batch_*.json")):
        verd.update(json.load(open(f)))
    out = {}
    for nid, m in key.items():
        if nid in items:
            out[(m["fam"], m["i"], m["arm"])] = (items[nid], verd.get(nid))
    return out


def load_famgen(tag):
    p = f"{FG}/famgen_{tag}.json"
    if not os.path.exists(p):
        return None
    return json.load(open(p))["families"]


def verdict_str(v):
    if not v:
        return "unjudged"
    return f"br {v['british']} · coh {v['coherence']} · eng {v['engaged']}"


def main():
    cj = load_cjudge()
    fam_cache = {tag: load_famgen(tag) for _, _, tag in LADDER if tag}

    L = ["# The `z` ladder on britishness, as text",
         "",
         "*Generated by `probefix/pf_addon_rollouts.py`; no re-sampling. `base` is the frozen model, "
         "every `z` row is that SAME frozen model plus `h_20 <- h_20 + z*A_20` (2560 trained "
         "parameters, `PREF=dpo`, 300 steps), and `P1 DPOP` is the ~21M-parameter LoRA comparator. "
         "Verdicts are the blind Claude judgements of `results/probefix_cjudge_zfine/` — all eight "
         "arms scored in ONE invocation, 768 items, 16 agents, 768/768 merged.*",
         "",
         "`br` = british 0-100 · `coh` = coherence 0-100 · `eng` = made the contested choice.",
         "",
         "Read for the thing no meter catches: the point on the ladder where the text stops "
         "answering the prompt and starts performing the register (`RESULTS_0818_MULTI_ADDON.md` §3).",
         ""]

    for fam in FAMS:
        idxs = sorted({i for (f, i, a) in cj if f == fam})
        def disagreement(i):
            a = cj.get((fam, i, "L20_z075"), (None, None))[1]
            b = cj.get((fam, i, "L20_z05"), (None, None))[1]
            if not a or not b:
                return -1
            return abs(a["british"] - b["british"])
        idxs.sort(key=lambda i: -disagreement(i))
        L += ["", "---", "", f"## {fam}", ""]
        for i in idxs:
            ref = cj.get((fam, i, "base"))
            if not ref:
                continue
            d = disagreement(i)
            L += [f"### {fam} #{i} — z0.75 vs z0.5 disagreement {d if d >= 0 else 'n/a'}", "",
                  f"**Prompt** — {ref[0]['prompt']}", "",
                  f"> British ref: *{ref[0]['british_ref']}*  ",
                  f"> American ref: *{ref[0]['american_ref']}*", ""]
            for label, arm, tag in LADDER:
                got = cj.get((fam, i, arm))
                if got:
                    gen, vs = got[0]["generation"], verdict_str(got[1])
                else:
                    fams = fam_cache.get(tag)
                    if not fams or fam not in fams:
                        continue
                    gen, vs = fams[fam]["gens"][i]["gen"], "unjudged"
                L += [f"**{label}** `{vs}`  ", gen.replace("\n", " ").strip(), ""]
    open(OUT, "w").write("\n".join(L) + "\n")
    print(f"-> {OUT}  ({len(L)} lines)")


if __name__ == "__main__":
    main()
